name: Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - run: make clean
      - run: docker compose up -d
      - run: make vendor
      - uses: actions/setup-python@v3
      - run: sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
      - run: sudo chmod +x /bin/hadolint
      - uses: pre-commit/action@v3.0.1
